### ISSUE TITLE
_payeesPaymentAddress missing from getRequestByTransactionHash() response

### ISSUE THREAD

**Issue by giltotherescue** [RequestNetwork/Request_App#3]
At Gilded we ran into an issue while attempting to re-use some of the code from the Payments angular app. Here's the specific error we had:

<img width="1060" alt="screen shot 2018-07-29 at 12 45 23 pm" src="https://user-images.githubusercontent.com/371250/43369263-aaf2e970-9330-11e8-8af1-5080fb27fbe1.png">

Basically, this error points to the following code:

https://github.com/RequestNetwork/Request_App/blob/master/src/app/util/web3.service.ts#L529

Typescript is complaining that `_payeesPaymentAddress` does not exist. I checked the response from `getRequestByTransactionHash()` and here is what I see:

<img width="835" alt="screen shot 2018-07-29 at 12 45 16 pm" src="https://user-images.githubusercontent.com/371250/43369288-fa0b21ee-9330-11e8-936c-3819f8f2c581.png">

Note that `_payeesPaymentAddress` is missing from the response, but `_payeesIdAddress` does exist.

Then I wondered whether it is because `paymentAddress` is missing [here](https://github.com/RequestNetwork/Request_App/blob/master/src/app/util/web3.service.ts#L301). I tried to add `paymentAddress` and create a new request, but still `_payeesPaymentAddress` does not exist in the response from `getRequestByTransactionHash()`.

## Temp Fix

I was able to work around this problem by populating the payment address if it does not exist yet. It is populated based on the ID address. Example:

```
currencyContract: {
        address: transaction.to,
        payeePaymentAddress: transaction.method.parameters._payeesPaymentAddress ?
            transaction.method.parameters._payeesPaymentAddress[0] : transaction.method.parameters._payeesIdAddress[0],
        payerRefundAddress: transaction.method.parameters._payerRefundAddress,
        subPayeesPaymentAddress: transaction.method.parameters._payeesPaymentAddress ?
            transaction.method.parameters._payeesPaymentAddress.slice(1) : transaction.method.parameters._payeesIdAddress.slice(1)
},
```

But why doesn't `getRequestByTransactionHash()` return `_payeesPaymentAddress` even when I specify it when creating the Request?

## Another potential issue

In the response I receive from `getRequestByTransactionHash()`, `_payeesIdAddress` is an array of strings. However, in the code below it seems that the first item from the array should also be an array. Should the `.slice()` call be removed? Also, should this be referencing `subPayeesPaymentAddress` instead of `_payeesIdAddress`? As far as I can tell, the `subPayees` code isn't even used.

https://github.com/RequestNetwork/Request_App/blob/master/src/app/util/web3.service.ts#L553

**Comment by giltotherescue** [comment]
I found several more issues with this `buildRequestFromCreateRequestTransactionParams()` function:

- Payer is empty because `transaction.method.parameters._payer` does not exist.
- The `state` property does not exist in the transaction, so future calls to `setRequestStatus()` fail. You can reference [here](https://github.com/RequestNetwork/Request_App/blob/master/src/app/invoices/request/request.component.ts#L122) and [here](https://github.com/RequestNetwork/Request_App/blob/master/src/app/invoices/request/request.component.ts#L178)

I modified [this line](https://github.com/RequestNetwork/Request_App/blob/master/src/app/invoices/request/request.component.ts#L124) to use `result.request` instead of the response from `buildRequestFromCreateRequestTransactionParams()`, and my app seems to be working much better. Do we need `buildRequestFromCreateRequestTransactionParams()` at all?

**Comment by Ellieutt** [comment]
Hi Gil, thanks for your feedbacks.
You can have a look at the latest commit, the issues regarding getRequestByTransactionHash method have been fixed.

The purpose of `buildRequestFromCreateRequestTransactionParams` function is to mock a request object while waiting for the transaction to be mined. `getRequestByTransactionHash` only returns a result containing the request information once the transaction has been mined.

**Comment by giltotherescue** [comment]
Thanks for the update!

Regarding the mock object, we actually ended up solving this in a different way. If there is no `requestId` yet, we return `false` from the `setRequest()` function. In that case, we don't show the Request details, but only a link to Etherscan to track the progress on the initial transaction.

Am closing this issue since you resolved the issued with `buildRequestFromCreateRequestTransactionParams`  👏👏👏
